In [6]:
#Ques-1-Hi I am new to Python numpy. Can you generate some real world situations where I can use a nampy array with some source code.
import numpy as np
sales = np.array([150, 350, 400, 450, 500, 550, 600, 650, 700])
totalsale = np.sum(sales)
print("Total sales:", totalsale)
average_sales = np.mean(sales)
print("Average sales:", average_sales)

Total sales: 4350
Average sales: 483.3333333333333


In [12]:
#Ques-2-Hi Let's create a real-life example involving weather data. Use NumPy to analyze temperature data for a week, perform slicing, 
#indexing, shaping, and reshaping operations, and calculate various statistics.
import numpy as np
# Temperature data
temperature_data = np.array([
    [15, 20, 18, 14],  
    [16, 21, 19, 15],  
    [14, 22, 17, 13],  
    [17, 23, 20, 16],  
    [18, 24, 21, 17],  
    [19, 25, 22, 18],  
    [20, 26, 23, 19]   
])

print("Temperature Data (Week):")
print(temperature_data)
# Slicing
noon_temperatures = temperature_data[:, 1]
print("\nNoon Temperatures (Week):")
print(noon_temperatures)
# Calculating statistics

mean_temperature_week = np.mean(temperature_data)
print("\nMean Temperature (Week):", mean_temperature_week)

max_temperature_week = np.max(temperature_data)
print("Max Temperature (Week):", max_temperature_week)

min_temperature_week = np.min(temperature_data)
print("Min Temperature (Week):", min_temperature_week)

mean_temperature_time_of_day = np.mean(temperature_data, axis=0)
print("\nMean Temperature (Time of Day):", mean_temperature_time_of_day)

max_temperature_time_of_day = np.max(temperature_data, axis=0)
print("Max Temperature (Time of Day):", max_temperature_time_of_day)

min_temperature_time_of_day = np.min(temperature_data, axis=0)
print("Min Temperature (Time of Day):", min_temperature_time_of_day)

# Indexing
day3_evening_temperature = temperature_data[2, 2]
print("\nTemperature on Day 3 (Evening):", day3_evening_temperature)

# Reshaping 
temperature_data_reshaped = temperature_data.reshape(-1)
print("\nReshaped Temperature Data (1D):")
print(temperature_data_reshaped)

# Reshaping
temperature_data_original_shape = temperature_data_reshaped.reshape(7, 4)
print("\nReshaped Back to Original (Week):")
print(temperature_data_original_shape)


Temperature Data (Week):
[[15 20 18 14]
 [16 21 19 15]
 [14 22 17 13]
 [17 23 20 16]
 [18 24 21 17]
 [19 25 22 18]
 [20 26 23 19]]

Noon Temperatures (Week):
[20 21 22 23 24 25 26]

Mean Temperature (Week): 19.0
Max Temperature (Week): 26
Min Temperature (Week): 13

Mean Temperature (Time of Day): [17. 23. 20. 16.]
Max Temperature (Time of Day): [20 26 23 19]
Min Temperature (Time of Day): [14 20 17 13]

Temperature on Day 3 (Evening): 17

Reshaped Temperature Data (1D):
[15 20 18 14 16 21 19 15 14 22 17 13 17 23 20 16 18 24 21 17 19 25 22 18
 20 26 23 19]

Reshaped Back to Original (Week):
[[15 20 18 14]
 [16 21 19 15]
 [14 22 17 13]
 [17 23 20 16]
 [18 24 21 17]
 [19 25 22 18]
 [20 26 23 19]]
