In [4]:
#NUMPY
#Numpy stands for "Numerical Pyhton".
#It is a famous python libarary for numerical and scientific computing.It provides support for working with large 
#multi-dimensional arrays and matrices of data along with a collection of mathematical function to operate on these arrays.
#Numpy is a fundamental library for data manipulation and analysis in python and is used in various fields such as data science and 
#machine learning etc.

In [41]:
#Shape and Dimension of a given array
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print("The rows and columns of a givebn array is:")
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

print("The number of dimensions a given array is:")
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

print("The values in the arrays are:")
print(a)
print(b)
print(c)
print(d)

The rows and columns of a givebn array is:
()
(5,)
(2, 3)
(2, 2, 3)
The number of dimensions a given array is:
0
1
2
3
The values in the arrays are:
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [36]:
import numpy as np 
arr=np.array([True,False,True],dtype=bool)
print(arr)

[ True False  True]


In [34]:
import numpy as np 
arr=np.array(['apple',2,3,5],dtype=object)
print(arr)

['apple' 2 3 5]


In [46]:
import numpy as np
arr=np.array(['hello','world'],dtype=np.string_)
print(arr)

[b'hello' b'world']


In [ ]:
#Copy and View in sql

In [2]:
import numpy as np
# l=[12,34,54,65,34,65]
arr=np.array([12,34,54,65,34,65])
arr2=arr[1:4]
print(arr)
print(arr2)

[12 34 54 65 34 65]
[34 54 65]


In [47]:
import numpy as np
# arr=np.zeros((5,3))+9
arr=np.ones((5,3))+9
fives=np.full(10,5,dtype=int)
print(arr)
print(fives)

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
[5 5 5 5 5 5 5 5 5 5]


In [20]:
import numpy as np
arr4 =np.eye(7)#It inserts 1 at diagonal of a given array according to the size.
print(arr4)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [22]:
import numpy as np 
rno=np.random.rand(4)#Random generates random number and rand gives the number of random numbers to generate.
print(rno)

[0.76828796 0.3497294  0.80226089 0.59124647]


In [34]:
#Reshape function
#The reshape function in NumPy allows you to change the shape (dimensions) of an array without changing
#its data.This can be useful when you want to rearrange the way data in an array ,such as converting a 1-D
#array in 2-d matrix or vice versa,or changing the size of a multi-dimensional array while maintaining the total number of elements.
arr=np.array([1,2,3,4,2,3,4,5,3,5,6,7])
arr=arr.reshape(4,3)
print(arr)
arr=arr.reshape(-1,12)
print(arr)

[[1 2 3]
 [4 2 3]
 [4 5 3]
 [5 6 7]]
[[1 2 3 4 2 3 4 5 3 5 6 7]]


In [40]:
import numpy as py
np.random.seed(10)
arr=np.random.randint(1,100,50)
print(arr)

[10 16 65 29 90 94 30  9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78
 70 14 26 14 93 87 31 31 90 13 66 32 58 37 28 19 94 78 23 24 95 12 29 75
 89 10]


In [50]:
#Slicing
arr=np.array([1,20,3,4,5,6,7,8,9,0,23,34,4,5,56,67,86,55])
slicing=arr[4:9]
print(slicing)
print(arr)
print(type(slicing))
print(type(arr))
slicing[:]=0
print(slicing)
print(arr)

[5 6 7 8 9]
[ 1 20  3  4  5  6  7  8  9  0 23 34  4  5 56 67 86 55]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0 0 0 0 0]
[ 1 20  3  4  0  0  0  0  0  0 23 34  4  5 56 67 86 55]


In [5]:
import numpy as np 
ar=np.arange(1,15)
print(ar)
print(ar[ar%2==0])
print(ar[ar%2!=0])
print(ar[ar>8])
ar[ar%2==0]=0
print(ar)
print("-----------------------------------------------------------------------------------------------------")
ar=np.arange(1,8)
print(ar+2)
print(ar*2)
print(ar**2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13]
[ 9 10 11 12 13 14]
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]
-----------------------------------------------------------------------------------------------------
[3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]


In [7]:
#functions in an array in numpy
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,99])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))

10
99
0
9
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669
 8.36660027 8.94427191 9.48683298 9.94987437]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485 -0.30481062
  0.77389068 -0.99388865  0.89399666 -0.99920683]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603 -0.95241298
  0.6333192  -0.11038724 -0.44807362  0.03982088]


In [13]:
#Row and column-wise operation functions 
import numpy as np

np.random.seed(122)
mat=np.random.randint(1,21,9).reshape(3,3)
print(mat)
print(np.sum(mat))
print(np.cumsum(mat))
print(np.min(mat))
print(np.max(mat))
print("---------------------------------------------------------")
print(np.sum(mat,axis=1))
print(np.min(mat,axis=1))
print(np.max(mat,axis=1))
print(np.cumsum(mat,axis=1))


[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
116
[ 16  27  40  57  70  86  89 105 116]
3
17
---------------------------------------------------------
[40 46 30]
[11 13  3]
[16 17 16]
[[16 27 40]
 [17 30 46]
 [ 3 19 30]]


In [ ]:
#User defined cumcum
import numpy as np

def fb(arr):
    row = arr.shape[0]
    col = arr.shape[1]
    arr2 = np.zeros((row, col))  # Initialize arr2 with zeros
    current_sum = 0
    
    for i in range(row):
        for j in range(col):
            current_sum += arr[i, j]
            arr2[i, j] = current_sum

    return arr2

# Reshape the array to 2D
arr = np.arange(1, 15).reshape((3, 5))
print(fb(arr))


In [27]:
#Shuffle
import numpy as np
np.random.seed(122)
mat=np.random.randint(1,21,10)
print(mat)
np.random.shuffle(mat)
print(mat) 
print(np.unique(mat,return_index=True,return_counts=True))
print(np.unique(mat).size)

[16 11 13 17 13 16  3 16 11 10]
[13 16 16 11 16 10 11 13 17  3]
(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8]), array([1, 1, 2, 2, 3, 1]))
6


In [45]:
#Stacking arrays Horizontally and Vertically
import numpy as np
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Vertically arranged array 1 and array 2")
print(np.vstack((arr1,arr2)))
print("Horizontally arranged array 1 and array 2")
print(np.hstack((arr1,arr2)))
print("---------------------------------------------------------------------")
#On 2-D array
import numpy as np
np.random.seed(122)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(1,21,9).reshape(3,3)

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Vertically arranged array 1 and array 2")
print(np.vstack((arr1,arr2)))
print("Horizontally arranged array 1 and array 2")
print(np.hstack((arr1,arr2)))

Array 1:
[10 20 30 40]
Array 2:
[50 60 70 80]
Vertically arranged array 1 and array 2
[[10 20 30 40]
 [50 60 70 80]]
Horizontally arranged array 1 and array 2
[10 20 30 40 50 60 70 80]
---------------------------------------------------------------------
Array 1:
[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
Array 2:
[[10  7 15]
 [ 4  5 20]
 [20 14  1]]
Vertically arranged array 1 and array 2
[[16 11 13]
 [17 13 16]
 [ 3 16 11]
 [10  7 15]
 [ 4  5 20]
 [20 14  1]]
Horizontally arranged array 1 and array 2
[[16 11 13 10  7 15]
 [17 13 16  4  5 20]
 [ 3 16 11 20 14  1]]
