In [4]:
#NUMPY
#Numpy stands for "Numerical Pyhton".
#It is a famous python libarary for numerical and scientific computing.It provides support for working with large 
#multi-dimensional arrays and matrices of data along with a collection of mathematical function to operate on these arrays.
#Numpy is a fundamental library for data manipulation and analysis in python and is used in various fields such as data science and 
#machine learning etc.

In [24]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print("The rows and columns of a givebn array is:")
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

print("The number of dimensions a given array is:")
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

print("The values in the arrays are:")
print(a)
print(b)
print(c)
print(d)

The rows and columns of a givebn array is:
()
(5,)
(2, 3)
(2, 2, 3)
The number of dimensions a given array is:
0
1
2
3
The values in the arrays are:
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [36]:
import numpy as np 
arr=np.array([True,False,True],dtype=bool)
print(arr)

[ True False  True]


In [34]:
import numpy as np 
arr=np.array(['apple',2,3,5],dtype=object)
print(arr)

['apple' 2 3 5]


In [46]:
import numpy as np
arr=np.array(['hello','world'],dtype=np.string_)
print(arr)

[b'hello' b'world']
