In [4]:
#NUMPY
#Numpy stands for "Numerical Pyhton".
#It is a famous python libarary for numerical and scientific computing.It provides support for working with large 
#multi-dimensional arrays and matrices of data along with a collection of mathematical function to operate on these arrays.
#Numpy is a fundamental library for data manipulation and analysis in python and is used in various fields such as data science and 
#machine learning etc.

In [24]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print("The rows and columns of a givebn array is:")
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

print("The number of dimensions a given array is:")
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

print("The values in the arrays are:")
print(a)
print(b)
print(c)
print(d)

The rows and columns of a givebn array is:
()
(5,)
(2, 3)
(2, 2, 3)
The number of dimensions a given array is:
0
1
2
3
The values in the arrays are:
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [36]:
import numpy as np 
arr=np.array([True,False,True],dtype=bool)
print(arr)

[ True False  True]


In [34]:
import numpy as np 
arr=np.array(['apple',2,3,5],dtype=object)
print(arr)

['apple' 2 3 5]


In [46]:
import numpy as np
arr=np.array(['hello','world'],dtype=np.string_)
print(arr)

[b'hello' b'world']


In [ ]:
#Copy and View in sql

In [2]:
import numpy as np
# l=[12,34,54,65,34,65]
arr=np.array([12,34,54,65,34,65])
arr2=arr[1:4]
print(arr)
print(arr2)

[12 34 54 65 34 65]
[34 54 65]


In [14]:
import numpy as np
# arr=np.zeros((5,3))+9
arr=np.ones((5,3))+9
print(arr)

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [20]:
import numpy as np
arr4 =np.eye(7)#It inserts 1 at diagonal of a given array according to the size.
print(arr4)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [22]:
import numpy as np 
rno=np.random.rand(4)#Random generates random number and rand gives the number of random numbers to generate.
print(rno)

[0.76828796 0.3497294  0.80226089 0.59124647]


In [34]:
#Reshape function
#The reshape function in NumPy allows you to change the shape (dimensions) of an array without changing
#its data.This can be useful when you want to rearrange the way data in an array ,such as converting a 1-D
#array in 2-d matrix or vice versa,or changing the size of a multi-dimensional array while maintaining the total number of elements.
arr=np.array([1,2,3,4,2,3,4,5,3,5,6,7])
arr=arr.reshape(4,3)
print(arr)
arr=arr.reshape(-1,12)
print(arr)

[[1 2 3]
 [4 2 3]
 [4 5 3]
 [5 6 7]]
[[1 2 3 4 2 3 4 5 3 5 6 7]]


In [40]:
import numpy as py
np.random.seed(10)
arr=np.random.randint(1,100,50)
print(arr)

[10 16 65 29 90 94 30  9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78
 70 14 26 14 93 87 31 31 90 13 66 32 58 37 28 19 94 78 23 24 95 12 29 75
 89 10]


In [50]:
#Slicing
arr=np.array([1,20,3,4,5,6,7,8,9,0,23,34,4,5,56,67,86,55])
slicing=arr[4:9]
print(slicing)
print(arr)
print(type(slicing))
print(type(arr))
slicing[:]=0
print(slicing)
print(arr)

[5 6 7 8 9]
[ 1 20  3  4  5  6  7  8  9  0 23 34  4  5 56 67 86 55]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0 0 0 0 0]
[ 1 20  3  4  0  0  0  0  0  0 23 34  4  5 56 67 86 55]
